# Generated by Django 5.2.6 on 2025-09-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0002_rename_agents_agent_delete_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
    ]
