# Generated by Django 5.2.6 on 2025-09-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0003_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user_name',
            new_name='name',
        ),
    ]
