# Generated by Django 5.2.6 on 2025-09-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0004_rename_user_name_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
    ]
